name: Update VPN Subscriptions

on:
  schedule:
    - cron: "0 */3 * * *" # هر 3 ساعت یکبار
  workflow_dispatch: # امکان اجرای دستی

permissions:
  contents: write # اجازه حیاتی برای پوش کردن تغییرات

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # دریافت تمام تاریخچه برای جلوگیری از تداخل

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pybase64 requests

      - name: Run script
        run: |
          cd Files
          python app.py

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions"
          author_email: "actions@github.com"
          message: "Auto Update Subscriptions"
          add: "." # اضافه کردن تمام فایل‌های جدید (پوشه‌های vmess و غیره)
          pull: "--rebase --autostash" # قبل از پوش کردن، تغییرات جدید را می‌گیرد تا تداخل ایجاد نشود
